syntax = "proto3";

import "google/protobuf/timestamp.proto";

package payment;
option java_package="com.derocode.payment";
option java_multiple_files=true;
option java_outer_classname="PaymentProto";

enum RequestPaymentMethod {
  PAYPAL=0;
  CREDIT_CARD=1;
  VISA_CARD=2;
  MASTER_CARD=3;
  AMERICAN_EXPRESS=4;
  DISCOVER_CARD=5;
  APPLE_PAY=6;
  GOOGLE_PAY=7;
  AMAZON_PAY=8;
  BITCOIN=9;
}

message GetPaymentRequest {
  int64 id=1;
}

message PaymentRequest {
  double amount=1;
  string paymentMethod=2;
  int64 orderId=3;
  string orderReference=4;
  string customerFirstName=5;
  string customerLastName=6;
  string customerEmail=7;
}

message PaymentResponse {
  optional int64 id=1;
  optional double amount=2;
  optional string paymentMethod=3;
  optional string status=4;
  optional int64 orderId=5;
  optional string orderReference=6;
  optional google.protobuf.Timestamp paymentDate=7;
}

service PaymentService {
  rpc CreatePayment(PaymentRequest) returns (PaymentResponse);
  rpc GetPayment(GetPaymentRequest) returns (PaymentResponse);
}