# ===============================
# Application
# ===============================
spring.application.name=grpc-payment-service

# ===============================
# AWS Secrets Manager (Postgres)
# ===============================
spring.config.import=aws-secretsmanager:${POSTGRES_DB_SECRET_NAME}?prefix=postgres.

# ===============================
# gRPC
# ===============================
spring.grpc.client.customer.host=${CUSTOMER_SERVICE_ADDR}
spring.grpc.client.customer.port=${GRPC_PORT}

spring.grpc.server.port=9090
spring.grpc.server.enable-reflection=true

# ===============================
# PostgreSQL Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://${postgres.host}/${postgres.dbname}?sslmode=verify-full&sslrootcert=/app/certs/rds-combined-ca-bundle.pem
spring.datasource.username=${postgres.username}
spring.datasource.password=${postgres.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-description=init
spring.flyway.baseline-version=0
spring.flyway.user=${postgres.username}
spring.flyway.password=${postgres.password}

# ===============================
# Kafka (MSK IAM Auth)
# ===============================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.ssl.endpoint.identification.algorithm=
spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM
spring.kafka.properties.security.protocol=SASL_SSL

# ===============================
# Optional Management / Tracing
# ===============================
# management.tracing.sampling.probability=1.0
# management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
